<!-- Platform Reports -->
<div class="d-flex justify-content-between align-items-center mb-4">
    <div>
        <h2 class="mb-1">
            <i class="fas fa-chart-bar text-primary me-2"></i>
            Platform Reports
        </h2>
        <p class="text-muted mb-0">Generate comprehensive reports and analytics</p>
    </div>
    <div>
        <button class="btn btn-primary" onclick="generateCustomReport()">
            <i class="fas fa-plus me-2"></i>Custom Report
        </button>
        <button class="btn btn-outline-secondary" onclick="location.reload()">
            <i class="fas fa-sync me-2"></i>Refresh
        </button>
    </div>
</div>

<!-- Quick Report Generation -->
<div class="row mb-4">
    <div class="col-lg-3 col-md-6 mb-3">
        <div class="card h-100">
            <div class="card-body text-center">
                <i class="fas fa-building fa-3x text-primary mb-3"></i>
                <h5>Tenant Report</h5>
                <p class="text-muted small">Comprehensive tenant analytics and performance metrics</p>
                <button class="btn btn-outline-primary" onclick="generateReport('tenant')">
                    <i class="fas fa-download me-1"></i>Generate
                </button>
            </div>
        </div>
    </div>
    
    <div class="col-lg-3 col-md-6 mb-3">
        <div class="card h-100">
            <div class="card-body text-center">
                <i class="fas fa-dollar-sign fa-3x text-success mb-3"></i>
                <h5>Financial Report</h5>
                <p class="text-muted small">Revenue, transactions, and financial performance analysis</p>
                <button class="btn btn-outline-success" onclick="generateReport('financial')">
                    <i class="fas fa-download me-1"></i>Generate
                </button>
            </div>
        </div>
    </div>
    
    <div class="col-lg-3 col-md-6 mb-3">
        <div class="card h-100">
            <div class="card-body text-center">
                <i class="fas fa-users fa-3x text-info mb-3"></i>
                <h5>User Activity Report</h5>
                <p class="text-muted small">User engagement, activity patterns, and behavior analysis</p>
                <button class="btn btn-outline-info" onclick="generateReport('user_activity')">
                    <i class="fas fa-download me-1"></i>Generate
                </button>
            </div>
        </div>
    </div>
    
    <div class="col-lg-3 col-md-6 mb-3">
        <div class="card h-100">
            <div class="card-body text-center">
                <i class="fas fa-shield-alt fa-3x text-warning mb-3"></i>
                <h5>Security Report</h5>
                <p class="text-muted small">Security incidents, fraud detection, and compliance metrics</p>
                <button class="btn btn-outline-warning" onclick="generateReport('security')">
                    <i class="fas fa-download me-1"></i>Generate
                </button>
            </div>
        </div>
    </div>
</div>

<!-- Recent Reports -->
<div class="row mb-4">
    <div class="col-lg-8">
        <div class="card">
            <div class="card-header">
                <h5 class="mb-0">
                    <i class="fas fa-history me-2"></i>
                    Recent Reports
                </h5>
            </div>
            <div class="card-body">
                <?php if (!empty($reports['recent'])): ?>
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>Report Name</th>
                                    <th>Type</th>
                                    <th>Generated By</th>
                                    <th>Date Range</th>
                                    <th>Status</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($reports['recent'] as $report): ?>
                                <tr>
                                    <td>
                                        <div class="fw-semibold"><?= htmlspecialchars($report['name'] ?? 'Unnamed Report') ?></div>
                                        <small class="text-muted"><?= htmlspecialchars($report['description'] ?? '') ?></small>
                                    </td>
                                    <td>
                                        <?php 
                                        $type = $report['type'] ?? 'custom';
                                        $typeClass = match($type) {
                                            'tenant' => 'bg-primary',
                                            'financial' => 'bg-success',
                                            'user_activity' => 'bg-info',
                                            'security' => 'bg-warning',
                                            default => 'bg-secondary'
                                        };
                                        ?>
                                        <span class="badge <?= $typeClass ?>"><?= ucfirst(str_replace('_', ' ', $type)) ?></span>
                                    </td>
                                    <td>
                                        <div><?= htmlspecialchars($report['generated_by'] ?? 'System') ?></div>
                                    </td>
                                    <td>
                                        <small><?= htmlspecialchars($report['date_range'] ?? 'N/A') ?></small>
                                    </td>
                                    <td>
                                        <?php 
                                        $status = $report['status'] ?? 'completed';
                                        $statusClass = match($status) {
                                            'completed' => 'bg-success',
                                            'generating' => 'bg-info',
                                            'failed' => 'bg-danger',
                                            default => 'bg-secondary'
                                        };
                                        ?>
                                        <span class="badge <?= $statusClass ?>"><?= ucfirst($status) ?></span>
                                    </td>
                                    <td>
                                        <div class="btn-group" role="group">
                                            <?php if (($report['status'] ?? '') === 'completed'): ?>
                                                <button class="btn btn-sm btn-outline-primary" onclick="downloadReport('<?= $report['id'] ?? 0 ?>')">
                                                    <i class="fas fa-download"></i>
                                                </button>
                                                <button class="btn btn-sm btn-outline-info" onclick="viewReport('<?= $report['id'] ?? 0 ?>')">
                                                    <i class="fas fa-eye"></i>
                                                </button>
                                            <?php endif; ?>
                                            <button class="btn btn-sm btn-outline-secondary" onclick="duplicateReport('<?= $report['id'] ?? 0 ?>')">
                                                <i class="fas fa-copy"></i>
                                            </button>
                                            <button class="btn btn-sm btn-outline-danger" onclick="deleteReport('<?= $report['id'] ?? 0 ?>')">
                                                <i class="fas fa-trash"></i>
                                            </button>
                                        </div>
                                    </td>
                                </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                <?php else: ?>
                    <div class="text-center py-5">
                        <i class="fas fa-chart-bar fa-3x text-muted mb-3"></i>
                        <h5>No Reports Generated</h5>
                        <p class="text-muted">Generate your first report to get started with analytics.</p>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
    
    <div class="col-lg-4">
        <div class="card">
            <div class="card-header">
                <h5 class="mb-0">
                    <i class="fas fa-cogs me-2"></i>
                    Report Settings
                </h5>
            </div>
            <div class="card-body">
                <div class="mb-3">
                    <label class="form-label">Default Date Range</label>
                    <select class="form-select" id="defaultDateRange">
                        <option value="7">Last 7 days</option>
                        <option value="30" selected>Last 30 days</option>
                        <option value="90">Last 90 days</option>
                        <option value="365">Last year</option>
                    </select>
                </div>
                
                <div class="mb-3">
                    <label class="form-label">Export Format</label>
                    <select class="form-select" id="exportFormat">
                        <option value="pdf">PDF</option>
                        <option value="excel">Excel</option>
                        <option value="csv">CSV</option>
                    </select>
                </div>
                
                <div class="form-check mb-3">
                    <input class="form-check-input" type="checkbox" id="includeCharts" checked>
                    <label class="form-check-label" for="includeCharts">
                        Include Charts
                    </label>
                </div>
                
                <div class="form-check mb-3">
                    <input class="form-check-input" type="checkbox" id="emailReport">
                    <label class="form-check-label" for="emailReport">
                        Email Report
                    </label>
                </div>
                
                <button class="btn btn-primary w-100" onclick="saveReportSettings()">
                    <i class="fas fa-save me-2"></i>Save Settings
                </button>
            </div>
        </div>
        
        <div class="card mt-4">
            <div class="card-header">
                <h5 class="mb-0">
                    <i class="fas fa-clock me-2"></i>
                    Scheduled Reports
                </h5>
            </div>
            <div class="card-body">
                <?php if (!empty($reports['scheduled'])): ?>
                    <?php foreach ($reports['scheduled'] as $scheduled): ?>
                    <div class="d-flex justify-content-between align-items-center mb-2">
                        <div>
                            <div class="fw-semibold"><?= htmlspecialchars($scheduled['name'] ?? 'Unnamed') ?></div>
                            <small class="text-muted"><?= htmlspecialchars($scheduled['frequency'] ?? 'Weekly') ?></small>
                        </div>
                        <div class="btn-group" role="group">
                            <button class="btn btn-sm btn-outline-primary" onclick="editScheduledReport(<?= $scheduled['id'] ?? 0 ?>)">
                                <i class="fas fa-edit"></i>
                            </button>
                            <button class="btn btn-sm btn-outline-danger" onclick="deleteScheduledReport(<?= $scheduled['id'] ?? 0 ?>)">
                                <i class="fas fa-trash"></i>
                            </button>
                        </div>
                    </div>
                    <?php endforeach; ?>
                <?php else: ?>
                    <p class="text-muted small">No scheduled reports configured.</p>
                <?php endif; ?>
                
                <button class="btn btn-outline-primary btn-sm w-100 mt-2" onclick="scheduleReport()">
                    <i class="fas fa-plus me-1"></i>Schedule Report
                </button>
            </div>
        </div>
    </div>
</div>

<!-- Report Generation Modal -->
<div class="modal fade" id="reportModal" tabindex="-1">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="reportModalTitle">Generate Report</h5>
                <button type="button" class="btn-close" data-coreui-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <form id="reportForm">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label for="reportName" class="form-label">Report Name</label>
                                <input type="text" class="form-control" id="reportName" name="name" required>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label for="reportType" class="form-label">Report Type</label>
                                <select class="form-select" id="reportType" name="type" required>
                                    <option value="">Select Type</option>
                                    <option value="tenant">Tenant Report</option>
                                    <option value="financial">Financial Report</option>
                                    <option value="user_activity">User Activity Report</option>
                                    <option value="security">Security Report</option>
                                    <option value="custom">Custom Report</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    
                    <div class="row">
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label for="startDate" class="form-label">Start Date</label>
                                <input type="date" class="form-control" id="startDate" name="start_date" required>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label for="endDate" class="form-label">End Date</label>
                                <input type="date" class="form-control" id="endDate" name="end_date" required>
                            </div>
                        </div>
                    </div>
                    
                    <div class="mb-3">
                        <label for="reportDescription" class="form-label">Description</label>
                        <textarea class="form-control" id="reportDescription" name="description" rows="2"></textarea>
                    </div>
                    
                    <div class="row">
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label for="reportFormat" class="form-label">Export Format</label>
                                <select class="form-select" id="reportFormat" name="format">
                                    <option value="pdf">PDF</option>
                                    <option value="excel">Excel</option>
                                    <option value="csv">CSV</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label for="emailTo" class="form-label">Email To (Optional)</label>
                                <input type="email" class="form-control" id="emailTo" name="email_to" placeholder="recipient@example.com">
                            </div>
                        </div>
                    </div>
                    
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" id="includeChartsModal" name="include_charts" checked>
                        <label class="form-check-label" for="includeChartsModal">
                            Include charts and visualizations
                        </label>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-coreui-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" onclick="submitReportGeneration()">Generate Report</button>
            </div>
        </div>
    </div>
</div>

<script>
function generateReport(type) {
    document.getElementById('reportType').value = type;
    document.getElementById('reportName').value = type.charAt(0).toUpperCase() + type.slice(1).replace('_', ' ') + ' Report';
    
    // Set default date range (last 30 days)
    const endDate = new Date();
    const startDate = new Date();
    startDate.setDate(startDate.getDate() - 30);
    
    document.getElementById('startDate').value = startDate.toISOString().split('T')[0];
    document.getElementById('endDate').value = endDate.toISOString().split('T')[0];
    
    const modal = new coreui.Modal(document.getElementById('reportModal'));
    modal.show();
}

function generateCustomReport() {
    document.getElementById('reportForm').reset();
    document.getElementById('reportModalTitle').textContent = 'Generate Custom Report';
    
    const modal = new coreui.Modal(document.getElementById('reportModal'));
    modal.show();
}

function submitReportGeneration() {
    const form = document.getElementById('reportForm');
    const formData = new FormData(form);
    
    console.log('Generating report:', Object.fromEntries(formData));
    
    // Close modal
    const modal = coreui.Modal.getInstance(document.getElementById('reportModal'));
    modal.hide();
    
    alert('Report generation started. You will be notified when it\'s ready.');
    location.reload();
}

function downloadReport(reportId) {
    console.log('Downloading report:', reportId);
    // Implementation for downloading report
}

function viewReport(reportId) {
    console.log('Viewing report:', reportId);
    // Implementation for viewing report
}

function duplicateReport(reportId) {
    console.log('Duplicating report:', reportId);
    alert('Report duplicated successfully!');
    location.reload();
}

function deleteReport(reportId) {
    if (confirm('Are you sure you want to delete this report?')) {
        console.log('Deleting report:', reportId);
        alert('Report deleted successfully!');
        location.reload();
    }
}

function saveReportSettings() {
    console.log('Saving report settings...');
    alert('Report settings saved successfully!');
}

function scheduleReport() {
    console.log('Scheduling report...');
    // Implementation for scheduling reports
}

function editScheduledReport(reportId) {
    console.log('Editing scheduled report:', reportId);
}

function deleteScheduledReport(reportId) {
    if (confirm('Are you sure you want to delete this scheduled report?')) {
        console.log('Deleting scheduled report:', reportId);
        alert('Scheduled report deleted successfully!');
        location.reload();
    }
}
</script>
